### PR TITLE
patch that make mouse enabled on the f12 menu

### PR DESCRIPTION
**Pull request by umjammer**
the original quasi88 can use mouse on the f12 menu.
i revive the mouse capability on the menu.

### CODE REVIEW

**Comment by barbeque** [comment]
Thank you so much for the contribution! It is hard to use the arrow keys on the F12 menu, so using the mouse is much better.

**Comment by umjammer** [comment]
not merged (´・ω・`)

**Comment by barbeque** [comment]
Oops

**Comment by barbeque** [comment]
Thank you! Sorry about that, it was early in the morning.

**Pull request merged**
